apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: neg-num
  name: neg-num-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: num-generator
        component: neg-num
    spec:
      containers:
      - image: neg-num-gen:v1
        name: neg-num
        ports:
        - containerPort: 8082
        resources:
          limits:
            cpu: 100m
