apiVersion: v1
kind: Service
metadata:
  labels:
    component: num-gen
  name: num-service
spec:
  ports:
  - port: 8082
  type: LoadBalancer
  selector:
    app: num-generator
    component: pos-num
