apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: pos-num
  name: pos-num-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: num-generator
        component: pos-num
    spec:
      containers:
      - image: pos-num-gen:v1
        name: pos-num
        ports:
        - containerPort: 8083
        resources:
          limits:
            cpu: 100m
